name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Define your inputs here.
inputs:
  file-path:
    description: Path to the results file
    required: true
    default: './results.json'

runs:
  using: node20
  main: dist/index.js
